# Script to deploy on Render

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
        
jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook@v2
      env:
        webhook_url: 'https://api.render.com/deploy/srv-cj5jrvoeba7s73ecr8f0?key=qR7dsN3ELxs'
        webhook_secret: 'qR7dsN3ELxs'
        
    - uses: bounceapp/render-action@0.6.0
      with:
        render-token: ${{secrets.RENDER_API_KEY}}
        github-token: ${{secrets.ACC_API_KEY}} #This is the github token
        service-id: "srv-cj5jrvoeba7s73ecr8f0" #Uique service ID from render. Don't cjhange it :)
        retires: 20
        wait: 16000
        sleep: 30000
  
